services:
  postgres:
    image: postgres:15
    container_name: lifekost_postgres
    restart: always
    environment:
      POSTGRES_USER: lifekost_user
      POSTGRES_PASSWORD: lifekost_pass
      POSTGRES_DB: lifekost_auth
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
